version: '2'
services:
  meapp-couchbase:
    build:
      context: .
      dockerfile: couchbase/Couchbase.Dockerfile
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 11210:11210
    environment:
      - TYPE=MASTER
      - BUCKET=meApp
  meapp-couchbase-node:
    build:
      context: .
      dockerfile: couchbase/Couchbase.Dockerfile
    environment:
      - TYPE=WORKER
      - BUCKET=meApp
      - COUCHBASE_MASTER=meapp-couchbase
      - AUTO_REBALANCE=false
